### ISSUE TITLE
Create Object Class

### ISSUE THREAD

**Issue by Todor-Shishmanov** [Todor-Shishmanov/Genesis#9]
**Describe what the feature will be:**

There are two types of items. Static and Interactive. 

For starters, we will need two static objects - Door and Wall. 
We can create a dynamic object Key just for reference.

They must be usable by the Character on the Map.

- [x] Wall
- [x] Door
- [x] Key

**Tasks:**
- [x] Concept
- [x] Tests
- [x] Implementation
- [x] Tech Docs

**Comment by mirela-manoleva** [comment]
The concept of an Object can be found [here](https://app.nuclino.com/TM-Game/Game-Docs/-Object-d4f3eda3-7aff-45bc-83a6-ac17b53b9ea7)

**Comment by Todor-Shishmanov** [comment]
Review of unit tests and header:

- Getters that are basically only returning private data should be named without the "get_" part for improved readability. E.g. `get_size()` -> `size()`. An exception to this rule can be the boolean private members. It is up to you if you want to change them. 

Line 29 in header:

       Type get_type() const;
       Type get_size() const;
       bool is_movable() const { return false; };
       bool is_collectable() const { return false; };
       bool is_destructible() const { return false; };
       double get_weight() const { return 0; };
       std::vector<Object*> get_contained() const { return std::vector<Object*>(); };`

- Just an idea - `std::string password`  can be `std::string pattern`. Firstly it matches the case - the key holds a pattern that unlocks the Door keyhole.  The Door's pattern can be used to regex match Keys. This allows different keys to be used for unlocking different Doors. In hotels, you have Manager keys used by the staff to unlock any Door. Now we can have happy hotel managers in our game too.

Line 76 in header:

     	std::string password;

- There should be default constructors for each Object. The default state of objects is a subjective matter, but for now, we can say - Key (that doesn't unlock anything), Door (that isn't unlocked) and Wall (which isn't movable or destructible). This will reduce the test code 10 times 😄. 

Line 17 in tests:

        Object::Size wSize = Object::Size::VeryBig;		
        bool wMovable = false;
	bool wCollectable = false;
	bool wDestructible = false;
	boat wWeight = 100;
	Wall wall(wSize, wMovable, wCollectable, wDestructible, wWeight);

        Object::Size kSize = Object::Size::VerySmall;
	bool kMovable = true;
	bool kCollectable = true;
	bool kDestructible = false;
	float kWeight = 2;
	std::string kPassword = "open";
	Key key(kSize, kMovable, kCollectable, kDestructible, kWeight, kPassword);

- Kind of on the same topic, we should add Door security.

- `TestObject` is a weird name as it can mean anything (the whole idea of `test_object.cpp` is to test objects) or nothing (there are no Object objects, no pun intended). As it will contain generic functionality tests you can call it `TestGeneral` or `TestGeneric`.

Line 11 in tests:

       TEST_CLASS(TestObject)

- No need for a for-loop when you know that you just created a Wall with no items contained. Also why not just assert `contained[1] == &key` ?

Line 33 in tests:

        std::vector<Object*> contained = wall.get_contained();
	bool found = false;
	for (size_t i = 0; i < contained.size(); i++) {
        	if (contained[i] == &key) {
			found = true;
			break;
		}
	}

	Assert::IsTrue(added, L"wall.add_contained_object(key) unsuccessful: did not return true");
	Assert::IsTrue(found, L"wall.add_contained_object(key) unsuccessful: did not add key to wall's objects");

-  Think about the equality, comparing by memory address isn't wrong by itself, but when items are stored as pointers the object must be responsible for invalidating every pointer that points to it when it gets deleted. This will get tricky with the current implementation. Maybe create a "parent"-like pointer? 

Line 77 in tests:

         contained[i] == &key

- Reading the tests it will be better if you make it clear that the Door and Key don't match. Maybe change `Open` to `Not Open` or something.

Line 196 in tests:

        std::string kPassword = "Open";

- Missing an Assert. Is that intentional? `Assert::AreEqual(previous_state, current_state, L"door.interact(wall) unsuccessful: the door changes state after using wall");` makes sense, no?

Line 223 in tests:

      Assert::IsFalse(door.interact(&wall), L"door.interact(wall) unsuccessful: did not return false");

**Comment by Todor-Shishmanov** [comment]
The review of the implementation is in the last commit, as comments. We should start creating branches.
